apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulk-nginx-8-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bulk-nginx-8
  template:
    metadata:
      labels:
        app: bulk-nginx-8
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8008
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-index
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-config
          configMap:
            name: bulk-nginx-8-configmap
        - name: nginx-index
          configMap:
            name: bulk-nginx-8-index
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bulk-nginx-8-configmap
data:
  default.conf: |
    server {
        listen 8008;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bulk-nginx-8-index
data:
  index.html: |
    <h1>Hello! I'm bulk-nginx-8! Yaay!</h1>
---
apiVersion: v1
kind: Service
metadata:
  name: bulk-nginx-8-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
  selector:
    app: bulk-nginx-8